# Generated by Django 4.1.3 on 2022-12-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='producer',
        ),
        migrations.AddField(
            model_name='movie',
            name='kp_rating',
            field=models.FloatField(default=0, verbose_name='KP-Rating'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(verbose_name='Your rating'),
        ),
    ]
