# Generated by Django 4.1.3 on 2022-12-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='kp_rating',
            field=models.FloatField(default=0, verbose_name='KP-Rating'),
            preserve_default=False,
        ),
    ]
