# Generated by Django 4.1.3 on 2022-12-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0002_wish_kp_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='kp_id',
            field=models.IntegerField(default=0, verbose_name='KP-ID'),
            preserve_default=False,
        ),
    ]
