# Generated by Django 4.1.3 on 2022-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0003_wish_kp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='year',
            field=models.CharField(default=0, max_length=4, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
